### ISSUE TITLE
Sprints for PyConDE & PyData Berlin 2019

### ISSUE THREAD

**Issue by alanderex** [PYCONDE/www#59]
Sprints planned for the PyConDE & Pydata Berlin 2019 conference.  
[https://de.pycon.org/sprints](https://de.pycon.org/sprints)

## Please add your sprint as **ONE** comment to this thread.
If you need to **add/edit** anything, **edit** your comment.

##### Group/Topic:
Stellar
##### Description 
Stellar is a commonly used package for counting stars in the sky. We plan to extend the package for counting black holes as well.
https://github.com/intergalactic/stellar
##### Contact 
enganged_dev@gmail.com (email), @enganged_dev (Twitter/Telegram)

### To create a new sprint, create a new comment and paste the below as template:

\#\#\#\#\# Group/Topic:

\#\#\#\#\# Description 

\#\#\#\#\# Contact

**Comment by alanjds** [comment]
##### Group/Topic:
RustPython

##### Description:
RustPython is a Python VM implemented in Rust.

We may work on porting some C-based modules from CPython, following the PEP-399. Or implementing features to the RustPython VM itself. Or anything else about it.

Personally, I am open to collaborate with alternative Python implementations to ease our combined work.

E.g:
- Re-use of standard library across implementations: https://discuss.python.org/t/re-use-of-standard-library-across-implementations/2051
- Insert RustPython on http://arewepythonyet.com/
- Work on RustPython integration with Cython

##### Contact

alan.justino@yahoo.com.br
@alanjds (twitter, github)
https://gitter.im/rustpython/Lobby

**Comment by serkef** [comment]
### Group/Topic
[Airflow](https://airflow.apache.org/)

### Description
Airflow is a platform to programmatically author, schedule and monitor workflows. It is widely used by data engineers, data analysts and data scientists to implement various data pipelines and workflows.
We are engaged with the community to prepare material for contributors with different background and expertise.

### Contact
sergiokef@gmail.com, @serkef (twitter/github)

**Comment by pylipp** [comment]
##### Group/Topic:
[`financeager`](https://github.com/pylipp/financeager)

##### Description
An application (possibly running as Flask webservice) that helps you administering your daily expenses and earnings. Interact via the command line interface.

The sprint offers the possibility to work on a variety of tasks:
- prepare for release 1.0.0
    - generalize database interface
    - prepare project for generating documentation using sphinx
    - extend documentation (e.g. REST API end points)
    - fix open issues
- experiment with TUI client
    - draft requirements and architecture
    - evaluate libraries (e.g. ptpython, urwid)

Note that due to personal availability, the sprint project takes place on Saturday only.

##### Contact
beth.aleph@yahoo.de, @pylipp (github)

**Comment by philippjfr** [comment]
##### Group/Topic:

[Panel](https://panel.pyviz.org)

##### Description

Panel is an open-source Python library that lets you create custom interactive web apps and dashboards by connecting user-defined widgets to plots, images, tables, or text.

In the sprint we will be working on:

- Putting together documentation for deployment on various cloud providers including AWS, GCP, DigitalOcean etc.
- Add new demos and examples to the gallery
- Fix open issues

##### Contact

prudiger@anaconda.com, @philippjfr (Twitter/GitHub)

**Comment by tine3700** [comment]
#### Group/Topic:
**[MicroPython](micropython.org)**
workshop/sprint for beginners in Python on hardware and experts in MicroPython curious to try new hardware
#### Description
MicroPython is a lean and efficient implementation of the Python 3 programming language that includes a small subset of the Python standard library and is optimised to run on microcontrollers and in constrained environments.
The MicroPython pyboard is a compact electronic circuit board that runs MicroPython on the bare metal, giving you a low-level Python operating system that can be used to control all kinds of electronic projects.

**The sprint/workshop will be split into two parts:**

**Beginners**

- Basic first steps.
- Connecting a microcontroller to your laptop.
- Communicating via a serial connection.
- Using the REPL (>>>) on the microcontroller.
- Testing it works!
- Setting a pin high (+3 volts)
- Detecting a pin is high (+3 volts)
 
**Advanced**

- In this workshop you will be learning to use the WiFi controller and running a tiny web server to display and consume web content.
- Download a WiFi manager and connect to a WiFi hotspot.
- Using a MicroWebSrv which is introduced by @nherriot during his talk on Wednesday
- Implement uasync instead of threading for the MicroWebSrerver
- Write tutorials, Fix open issues

**What We Will Supply**

We will be offering a range of MicroPython hardware and sensors to play with. Including our new **PYBOARD D** and accessories. So if you are interested, drop by and say hello.

**What You Need**

- If possible please bring a Linux PC to try code and hardware. This should have one free standard USB socket. You need to have SUDO writes to install software and be able to change user group settings on the machine (i.e. DIALOUT)
- If you would like to read more about the workshop, have a look [HERE](https://github.com/SamsungResearchUK-IoT-Meetup/multimode_sensor_platform/wiki/PyCon-DE-Micropython-Workshop-2019)

If you want to see some tutorials now have a look [HERE](http://docs.micropython.org/en/latest/pyboard/tutorial/script.html)

**Everyone interested in MicroPython is very welcome and we especially encourage women and non binary people.**

#### Contact

Christine christine@micropython.org, @micropython (twitter)
Nicholas nicholas.herriot@gmail.com, n.herriot@samsung.com, @NicholasHerriot (twitter)

**Comment by jtpio** [comment]
#### Group / Topic

[Voilà](https://github.com/voila-dashboards/voila)

#### Description

Voilà is an open source tool that turns Jupyter notebooks into standalone web applications.

Voilà is built upon Jupyter standard protocols and file formats and works with any Jupyter kernel (C++, Python, Julia), making it a language-agnostic dashboarding system.

Voilà also supports Jupyter interactive widgets, including the roundtrips to the kernel.

During the sprint, we will be working on:

- Tackling [good first issues](https://github.com/voila-dashboards/voila/labels/good%20first%20issue).
- Adding new examples to the [Voilà Gallery](https://voila-gallery.org).
- Create custom templates for Voilà to create modern and responsive web applications. And example is [voila-vuetify](https://github.com/voila-dashboards/voila-vuetify).

#### Contact

Jeremy Tuloup | jeremy.tuloup@quantstack.net | @jtpio (Twitter & GitHub)

**Comment by ctheune** [comment]
##### Group/Topic:

Flying Circus / batou

![batou](https://batou.readthedocs.io/en/latest/_static/batou.png)

##### Description

batou is a BSD licensed utility, written in Python, to configure development and production environments for web applications.

Deployments are hard and complicated. Tools like Docker, Puppet, chef, and others exist that try to solve this problem once and for all. However, they usually need you to change your workflow or toolchain massively while still missing important steps.

batou makes deployments more bearable without requiring developers to change their applications. It provides a “one command” approach that should never need additional wrapper scripts.

During the sprint, we will work on

* finishing up porting batou to Python 3
* extend our documentation

##### Contact
 
Christian Theune | ct@flyingcircus.io | @theuni (Twitter & Github)

**Comment by timhoffm** [comment]
##### Group/Topic

pptx-blueprint - The birth of a project


##### Description

PowerPoint is great for layouting, but annoying if you have to update/insert data repeatedly. So let's layout in PowerPoint and use Python to fill in the data.

![pptx-blueprint](https://user-images.githubusercontent.com/2836374/66477238-e38ada80-ea97-11e9-846b-a02b7ecb0f26.png)

with code like

~~~
from pptxblueprint import Template

tpl = Template('conference_stats.pptx')

tpl.slides[1].insert_text('#title', 'PyCon.DE 2019')
tpl.slides[1].insert_text('#location', 'Berlin')
tpl.slides[1].insert_text('#date', '9-13 October 2019')

tpl.slides[1].insert_image('#logo', 'pyconde2019.png')

stats = {
    'Attendees': 1111,
	'Waiting List': '800+',
	'Sessions': '100+',
	'Sponsors': 32
}
tpl.slides[1].insert_table('#table', stats)

tpl.save('PyCon_DE_2019.pptx')
tpl.export('PyCon_DE_2019.pdf')
~~~

So far, this is only an idea. No code exists yet. In the spint we'll jointly:

- Set up the project
- Discuss user needs
- Discuss a suitable API
- Define the templating scheme
- Implement a first prototype of the project.

Everybody is welcome; from people with software design experience to novices who want to see how one can approach such a project.

##### Contact
tim.hoffmann@mailbox.org, @timhoffm (github)

**Comment by adrinjalali** [comment]
![scikit-learn-logo-small](https://user-images.githubusercontent.com/1663864/66547205-02907780-eb3f-11e9-8801-c12945fdeff3.png)

##### Group/Topic:
[scikit-learn](https://scikit-learn.org/dev/) 

##### Description
`scikit-learn` is a machine learning library (https://github.com/scikit-learn/scikit-learn) developed by volunteers, and I'll be there as one of the maintainers of the package.

I can help you set up a development environment and find you some good first time issues and get you started :)

Please do read https://scikit-learn.org/dev/developers/contributing.html#ways-to-contribute beforehand if you intend to attend. If not, I'll help you find the relevant parts at the sprint.

##### Contact
https://github.com/adrinjalali/

**Comment by katsar0v** [comment]
##### Group/Topic: Improve and extend the documentation from JupyterLab

##### Description

The idea is to work on the official documentation on JupyterLab, which I think lot's of developers woud agree, could be really improved. There is an official issue on this topic - https://github.com/jupyterlab/jupyterlab/issues/7273 and working on this issue in a sprint environment would help improving the documentation drastically.

I can help figuring out use cases, looking the documentation from another perspective, so that the documentation is easier to understand and more understandable for new developers. In the mentioned issue, some use cases were mentioned, that are not answered in the official documentation: 

> How do I find out if a notebook has loaded?
> How do I find out if a notebook has changed or another file has been loaded?
> How do I find out if the kernel has been interrupted or has resumed working?
> How do I attach events when a cell is executed / deleted / created?
> How do I attach events when the path in file manager is changed?
> How do I open a notebook/file manually? (via code)

I think we can write some great answers and contribute to the jupyter community.

##### Contact

https://github.com/katsar0v/

**Comment by PythonLinks** [comment]
##### Group/Topic:
Indexing Lightning Talks about Python Open Source Software

##### Description
There is so much great open source software, but it is hard to find it.  People love ightning talks,  but there are often 12 lightning talks in a single YouTube Video, with no description of each lighting talk, and no way to search  the descriptions, or vote on the talk. 

At this sprint, I want to visit all of the represented open source projects, and make sure that their best lightning talks are indexed.   That will not take long, so the rest of the time, I would like to index other great lightning talks which you might recommend. 

Here you can see the index of the [EuroPython 2019 Lightning Talks](https://pythonlinks.info/europython-2019-lightning-talks?sortBy=bestWilsonScore).


##### Contact
lozinski@PythonLinks.info

**Comment by timnon** [comment]
# Group/Topic:

Lets make a version of the well-known book: ["Probabilistic Programming and Bayesian Methods for Hackers"](https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers) for [NumPyro](https://github.com/pyro-ppl/numpyro).

# Description:

NumPyro is a relatively new Probabilistic Programming framework based on [Jax](https://github.com/google/jax), but it looks promising (Disclaimer: i am not involved in the development of NumPyro). There is relatively little documentation so far, so it would be nice to create a version of the famous ["Probabilistic Programming and Bayesian Methods for Hackers"](https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers)  for NumPyro and learn+test it on the way. 

# Contact
Please contact me before if you are interested:  tim@nonner.de @timnon (github)

**Comment by mattpap** [comment]
##### Group/Topic:

<img src="https://static.bokeh.org/logos/logotype.svg" height="60" width="150" alt="Bokeh" />

##### Description

[Bokeh](https://bokeh.pydata.org) is an interactive visualization library that targets modern web browsers for presentation. Its goal is to provide elegant, concise construction of versatile graphics, and to extend this capability with high-performance interactivity over very large or streaming datasets. Bokeh can help anyone who would like to quickly and easily create interactive plots, dashboards, and data applications.

In this sprint we will be working on:

* improving developers' documentation
* improving support for mobile/touch devices
* statically typing of bokeh's codebase

##### Contact

mateusz@bokeh.org, @mattpap
